name: py

on:
  schedule:
    - cron: "* * * * *"  # Runs at 11:30 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the Python version needed
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Execute Python script
        run: |
          python main.py
