name: py

on:
  schedule:
    - cron: "15 2 * * *"  
  workflow_dispatch:
    inputs:
      branch:
        description: 'Run tests on branch'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Execute Python script
        run: |
          python main.py
